### ISSUE TITLE
rapidxml.hpp syntax error

### ISSUE THREAD

**Issue by posmicanomaly** [thebracket/rltk#10]
Visual Studio 2017 using toolset v141 for project, generated with cmake.

https://github.com/thebracket/rltk/issues/8 referenced cereal not included, I copied the folder to my 3rd_party collection for VS, then encountered this error. Unsure how to proceed.

1>C:\dev\Cpp\3rd_party\header\cereal/external/rapidxml/rapidxml.hpp(398): error C2059: syntax error: '<parameter-list>'
1>C:\dev\Cpp\3rd_party\header\cereal/external/rapidxml/rapidxml.hpp(652): note: see reference to class template instantiation 'cereal::rapidxml::memory_pool<Ch>' being compiled
1>C:\dev\Cpp\3rd_party\header\cereal/external/rapidxml/rapidxml.hpp(398): error C2238: unexpected token(s) preceding ';'

**Comment by thebracket** [comment]
I'll give this a look as soon as I get VS2017 updated on my laptop (I normally use MSYS2; I primarily develop on Mac/Linux, so my typical workflow is to get it working on there and then compile on Windows in a UNIX-like environment). I've had it compile on VS before, so I know it can be done - I just don't remember what the magical incantation was.

**Comment by gunnar-schulze** [comment]
I encountered similar problems on compiling rapidxml under Visual Studio 17. They could be settled by specifying the typedef in line 385 of rapidxml.hpp more exactly by adding an additional pair of parentheses:
`typedef void *((alloc_func)(std::size_t));`
