### ISSUE TITLE
Command line error D8021: invalid numeric argument '/Wpedantic'

### ISSUE THREAD

**Issue by posmicanomaly** [thebracket/rltk#11]
Visual Studio 2017 v141 toolset

3>cl : Command line error D8021: invalid numeric argument '/Wpedantic'

Removing -Wpedantic from CMakeLists.txt allows me to continue with build.

**Comment by thebracket** [comment]
Looks like I messed up the CMakeLists.txt file; it should offer different options between gcc/clang and Visual Studio, and that seems to have been eaten somewhere along the lines. I'll get that fixed this week.
