### ISSUE TITLE
Setting up on mac OS

### ISSUE THREAD

**Issue by hexstr1p** [thebracket/rltk#13]
The install is pretty straight forward.
`brew install sfml`
`brew install cereal`
in Xcode Build Phases > Linke Binary with Libraries add all of the .dylibs in 
`/usr/local/Cellar/sfml/2.4.2_1/lib/`
in Build Settiings > Search Paths > Header Search Paths add these
`/usr/local/Cellar/sfml/2.4.2_1/include`
`/usr/local/Cellar/cereal/1.2.2/include`
in Build Settiings > Search Paths > Library Search Paths add this
`/usr/local/Cellar/sfml/2.4.2_1/lib`
Download the latest sfml for mac from `https://www.sfml-dev.org/download.php`
and copy the full contents of `SFML-2.4.2-osx-clang/lib/` and `SFML-2.4.2-osx-clang/extlib/` to
`/Library/Frameworks/`
and finally, add all of the contents of `rltk-master/rltk` to your Xcode project.

After all of that, I still get this error when trying to compile the provided example1
```
Undefined symbols for architecture x86_64:
  "_gzclose", referenced from:
      rltk::xp::rex_sprite::rex_sprite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in rexspeeder.o
      rltk::xp::rex_sprite::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in rexspeeder.o
  "_gzeof", referenced from:
      rltk::s_gzread(gzFile_s*, void*, unsigned int) in rexspeeder.o
  "_gzerror", referenced from:
      rltk::s_gzopen(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*) in rexspeeder.o
      rltk::make_rexception(gzFile_s*) in rexspeeder.o
  "_gzflush", referenced from:
      rltk::xp::rex_sprite::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in rexspeeder.o
  "_gzopen", referenced from:
      rltk::s_gzopen(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*) in rexspeeder.o
  "_gzread", referenced from:
      rltk::s_gzread(gzFile_s*, void*, unsigned int) in rexspeeder.o
  "_gzwrite", referenced from:
      rltk::s_gzwrite(gzFile_s*, void*, unsigned int) in rexspeeder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thebracket** [comment]
I don't have homebrew (brew) on my hackintosh to test this, but the error message tells me that `zlib` needs to be installed. The REX Paint file format compresses everything, and the REXSpeeder code (originally from Pyradine, I believe) uses it do decompress the files.

**Comment by hexstr1p** [comment]
Awesome. In that case the next steps are
`brew install zlib`
then link the `/usr/local/Cellar/zlib/x.y.z/lib/libz.x.y.z.dylib` in Build Phases.
Now it compiles successfully.
